services:
  - type: web
    name: movie-recommendation-system
    env: python
    plan: free
    buildCommand: |
      pip install -U pip
      pip install -e ".[dev]"
      python -m mrs.pipelines.train --run-id prod
    startCommand: |
      uvicorn mrs.serving.api:app --host 0.0.0.0 --port $PORT
